version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-gif-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WORKERS=${WORKERS}
    env_file:
      - ./.env
    volumes:
      - ./assets/gifs:/app/assets/gifs